package dji.v5.ux.core.base.charts.formatter;

import dji.v5.ux.core.base.charts.model.AxisValue;

public interface AxisValueFormatter {
    int formatValueForManualAxis(char[] var1, AxisValue var2);

    int formatValueForAutoGeneratedAxis(char[] var1, float var2, int var3);
}
